name: Fedora 32

on:
  push:
    branches-ignore: [main]
    paths:
      - ".github/workflows/fedora32.yml"
      - "Fedora/fedora32.json"
  pull_request:
    branches: [develop, main]
    paths:
      - ".github/workflows/fedora32.yml"
      - "Fedora/fedora32.json"

jobs:
  build:
    runs-on: macos-10.15
    env:
      DISTRO: Fedora
      TEMPLATE: fedora32.json

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/cache@v2
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
          pip install pre-commit

      - name: Validate Ansible Version
        run: ansible --version

      - name: Validate Packer Version
        run: packer --version

      - name: Validate VirtualBox Version
        run: VBoxManage --version

      - name: Validate Packer Template
        run: |
          cd $DISTRO
          packer validate -syntax-only $TEMPLATE
